wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 32
conv_filters:
  value:
  - 16
  - 32
  - 64
  - 128
  - 256
dense_neurons:
  value: 256
epochs:
  value:
  - 15
  - 20
  - 35
  - 50
kernel_sizes:
  value:
  - 7
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.004224811674636789
use_augmentation:
  value: true
