wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
conv_filters:
  value:
  - 16
  - 32
  - 64
  - 128
  - 256
dense_neurons:
  value: 1024
epochs:
  value: 15
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.000804143163679111
use_augmentation:
  value: true
