wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 64
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 512
dense_neurons:
  value: 1024
epochs:
  value: 15
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 5
  - 5
learning_rate:
  value: 0.0004994741268773188
use_augmentation:
  value: false
