wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 16
conv_filters:
  value:
  - 32
  - 64
  - 64
  - 32
  - 32
dense_neurons:
  value: 512
epochs:
  value: 15
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0066286564317215154
use_augmentation:
  value: true
