wandb_version: 1

activation:
  value: silu
batch_size:
  value: 128
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 512
dense_neurons:
  value: 256
epochs:
  value:
  - 15
  - 20
  - 35
  - 50
kernel_sizes:
  value:
  - 7
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.003492736378093483
use_augmentation:
  value: true
