wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 16
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 512
dense_neurons:
  value: 1024
epochs:
  value:
  - 15
  - 20
  - 35
  - 50
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 5
  - 5
learning_rate:
  value: 0.00020548989721618053
use_augmentation:
  value: false
