wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
conv_filters:
  value:
  - 32
  - 64
  - 64
  - 32
  - 32
dense_neurons:
  value: 256
epochs:
  value: 15
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0009049834041929808
use_augmentation:
  value: false
