wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
conv_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
dense_neurons:
  value: 1024
epochs:
  value: 15
kernel_sizes:
  value:
  - 5
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0012166976499517106
use_augmentation:
  value: false
