wandb_version: 1

activation:
  value: silu
batch_size:
  value: 16
conv_filters:
  value:
  - 32
  - 64
  - 64
  - 32
  - 32
dense_neurons:
  value: 1024
epochs:
  value: 15
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.001395180995022696
use_augmentation:
  value: false
