wandb_version: 1

activation:
  value: silu
batch_size:
  value: 32
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 512
dense_neurons:
  value: 256
epochs:
  value: 15
kernel_sizes:
  value:
  - 5
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.006081922443950539
use_augmentation:
  value: true
