wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
conv_filters:
  value:
  - 16
  - 32
  - 64
  - 128
  - 256
dense_neurons:
  value: 512
epochs:
  value: 15
kernel_sizes:
  value:
  - 5
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.00038783753377842346
use_augmentation:
  value: false
