wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 512
dense_neurons:
  value: 256
epochs:
  value: 15
kernel_sizes:
  value:
  - 5
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.005191159351774325
use_augmentation:
  value: true
