wandb_version: 1

activation:
  value: mish
batch_size:
  value: 32
conv_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
dense_neurons:
  value: 256
epochs:
  value: 15
kernel_sizes:
  value:
  - 7
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.00020958266203317629
use_augmentation:
  value: true
