wandb_version: 1

activation:
  value: silu
batch_size:
  value: 64
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 512
dense_neurons:
  value: 1024
epochs:
  value: 15
kernel_sizes:
  value:
  - 5
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.007534119183136438
use_augmentation:
  value: true
