wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 32
conv_filters:
  value:
  - 32
  - 64
  - 64
  - 32
  - 32
dense_neurons:
  value: 512
epochs:
  value: 15
kernel_sizes:
  value:
  - 5
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0009134720942880562
use_augmentation:
  value: true
