wandb_version: 1

activation:
  value: mish
batch_size:
  value: 64
conv_filters:
  value:
  - 32
  - 32
  - 64
  - 64
  - 128
dense_neurons:
  value: 256
epochs:
  value:
  - 15
  - 20
  - 35
  - 50
kernel_sizes:
  value:
  - 7
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.00010119058792898388
use_augmentation:
  value: false
