wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 64
conv_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
dense_neurons:
  value: 512
epochs:
  value: 15
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0001129669909079087
use_augmentation:
  value: true
