wandb_version: 1

activation:
  value: silu
batch_size:
  value: 64
conv_filters:
  value:
  - 32
  - 64
  - 64
  - 32
  - 32
dense_neurons:
  value: 1024
epochs:
  value: 15
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 5
  - 5
learning_rate:
  value: 0.0006140042848671586
use_augmentation:
  value: true
