wandb_version: 1

activation:
  value: mish
batch_size:
  value: 8
conv_filters:
  value:
  - 16
  - 32
  - 64
  - 128
  - 256
dense_neurons:
  value: 1024
epochs:
  value:
  - 15
  - 20
  - 35
  - 50
kernel_sizes:
  value:
  - 5
  - 5
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0001095766783683672
use_augmentation:
  value: true
