wandb_version: 1

activation:
  value: silu
batch_size:
  value: 64
conv_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
dense_neurons:
  value: 1024
epochs:
  value:
  - 15
  - 20
  - 35
  - 50
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.006004932321405285
use_augmentation:
  value: false
